# Generated by Django 4.2.27 on 2026-01-03 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itanery_app', '0006_alter_customer_id_alter_flight_id_alter_hotel_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerary',
            name='icon',
            field=models.CharField(choices=[('📍', '📍 Location'), ('🏨', '🏨 Hotel'), ('🏛️', '🏛️ Monument'), ('🛍️', '🛍️ Shopping'), ('🌙', '🌙 Night'), ('✈️', '✈️ Flight'), ('🧳', '🧳 Luggage'), ('🚢', '🚢 Cruise'), ('🗺️', '🗺️ Map')], default='📍', help_text='Choose an icon for this day', max_length=10),
        ),
    ]
